# Generated by Django 4.2.3 on 2023-08-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey("customers.Customer", on_delete=models.CASCADE, default=3), 
        ),
    ]
