# Generated by Django 4.2.3 on 2023-08-12 16:45

import customers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('address', models.TextField(verbose_name='address')),
                ('avatar', models.ImageField(blank=True, help_text='Upload an avatar image (max 1MB).', max_length=1024, null=True, upload_to='customer/avatars/', validators=[customers.models.validate_image_file_size], verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
