# Generated by Django 4.2.3 on 2023-08-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
