# Generated by Django 4.2.3 on 2023-08-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_customer'),
        ('customers', '0002_remove_customer_email_customer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='orders.order'),
        ),
    ]
