# Generated by Django 4.2.3 on 2023-08-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_categorymenuitem_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymenuitem",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
        ),
    ]
