# Generated by Django 4.2.3 on 2023-08-06 15:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={},
        ),
        migrations.AddField(
            model_name='courier',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='courier',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='coordinates'),
        ),
    ]
