# Generated by Django 4.2.3 on 2023-08-15 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couriers', '0002_alter_courier_options_courier_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
