# Generated by Django 4.2.3 on 2023-08-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0006_alter_courier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='phone',
        ),
    ]
