# Generated by Django 4.2.3 on 2023-08-20 04:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("couriers", "0008_alter_courier_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="coordinates"
            ),
        ),
    ]
